# Generated by Django 5.1.5 on 2025-02-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='factory_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
